CREATE TABLE atom3(
	idx INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	ano VARCHAR(20),
	name VARCHAR(20) NOT null,
	balance INT DEFAULT 0
);

DESC atom3;
INSERT INTO atom3 VALUES(DEFAULT, 1111, "홍길동",DEFAULT);

SELECT * FROM atom3;
SELECT 

UPDATE atom3 SET ano = 1234 WHERE NAME = "홍길동";